name: ETL Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'data/raw/**'
      - 'etl/**'
      - 'Makefile'
      - 'requirements-ci.txt'

jobs:
  etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-ci.txt
        pip install dvc

    - name: Run ETL pipeline
      run: |
        make clean

    - name: Commit and push cleaned data
      run: |
        dvc add data/clean/train_clean.csv
        dvc add data/clean/test_clean.csv
        git add data/clean/train_clean.csv.dvc data/clean/test_clean.csv.dvc .gitignore
        git commit -m "Automated ETL: Update cleaned data" || echo "No changes to commit"
        dvc push
        git push origin main



